### ISSUE TITLE
Hard coded path in SatisfiabilityEntailmentChecker

### ISSUE THREAD

**Issue by tudorache** [matthewhorridge/owlexplanation#7]
It seems that the code is trying to write to a hard coded path (\tmp\lasterror.owl) that may not exist in the filesystem.

Reported on the mailing list.

```
C:\Users\xxx\Protege-5.0.0-beta-17>jre\bin\java -Dlog4j.configuration=file:l
og4j.xml -DentityExpansionLimit=100000000 -Dfile.encoding=utf-8 -Dorg.protege.pl
ugin.dir=plugins -classpath bin/org.apache.felix.main.jar;bin/ProtegeLauncher.ja
r org.protege.osgi.framework.Launcher
Starting Protege Desktop (Version 5.0.0, Build = beta-17)
Platform:
    Java: JVM 1.8.0_40-b26 Memory: 1877M
    Language: en, Country: US
    Framework: Apache Software Foundation (1.7)
    OS: windows7 (6.1)
    Processor: x86-64
Plugin: Snorocket Reasoner (2.7.4)
Plugin: Cajun Visualization Library (1.0.2)
Plugin: Guava: Google Core Libraries for Java (18.0.0)
Plugin: DL Query (2.0.2)
Plugin: OWLViz (4.1.4)
Plugin: OWL Code Generation Plug-in (1.0.2)
Plugin: OWL Difference (5.0.0)
Plugin: Protege Editor OWL (5.0.0.beta-17)
Plugin: Protege SPARQL Plugin (1.0.0)
Plugin: Explanation Workbench (2.0.0)
Plugin: Protege HermiT Integration (1.0.0)
Plugin: OntoGraf (1.0.3)
Plugin: OWL Difference Engine (2.0.0)
Plugin: OWLAPI RDF Library (1.0.2)
Plugin: snap-sparql-query-plugin;singleton:=true (1.0.0.SNAPSHOT)
Plugin: HermiT Reasoner (1.3.8)
Plugin: owlapi-osgidistribution (3.5.1)
Plugin: Factplusplus Plug-in (1.6.4)
Plugin: BeanShell (1.1.1)
Plugin: URI Utilities (1.1.1)
        Cajun Visualization Library Plugin has no plugin.xml resource
        Guava: Google Core Libraries for Java Plugin has no plugin.xml resource
        OWL Difference Engine Plugin has no plugin.xml resource
        OWLAPI RDF Library Plugin has no plugin.xml resource
        owlapi-osgidistribution Plugin has no plugin.xml resource
Using OWL API version 3.5.1
Rebuilding entity indices...
... rebuilt in 10 ms
Setting active ontology to OntologyID(OntologyIRI(<http://www.semanticweb.org/am
allia/ontologies/2015/9/untitled-ontology-75>))
Rebuilding entity indices...
... rebuilt in 0 ms
... active ontology changed
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/amal
lia/ontologies/2015/9/untitled-ontology-75
Setting active ontology to OntologyID(OntologyIRI(<http://www.semanticweb.org/am
allia/ontologies/2015/9/untitled-ontology-75>))
Rebuilding entity indices...
... rebuilt in 0 ms
... active ontology changed
Auto-update last performed: Thu Oct 08 12:08:53 EDT 2015
Auto-update has not been performed today.  Running it.
Using OWL API version 3.5.1
Rebuilding entity indices...
... rebuilt in 0 ms
Using OWL API version 3.5.1
Rebuilding entity indices...
... rebuilt in 0 ms
Adding root folder: C:\Users\amallia\ontologies ...
        ...done
loading OntologyID(Anonymous-0) from file:/C:/Users/amallia/ontologies/FHIR.ttl
Setting active ontology to OntologyID(OntologyIRI(<http://hl7.org/fhir>))
Rebuilding entity indices...
... rebuilt in 0 ms
... active ontology changed
Setting active ontology to OntologyID(OntologyIRI(<http://hl7.org/fhir>))
Rebuilding entity indices...
... rebuilt in 0 ms
... active ontology changed
Initializing the reasoner by performing the following steps:
        class hierarchy
        object property hierarchy
        data property hierarchy
        class assertions
        object property assertions
        data property assertions
HermiT 1.3.8.3 classified in 1546ms
java.io.FileNotFoundException: \tmp\lasterror.owl (The system cannot find the pa
th specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.semanticweb.owl.explanation.impl.blackbox.checker.SatisfiabilityE
ntailmentChecker.isEntailed(SatisfiabilityEntailmentChecker.java:272)
       at org.semanticweb.owl.explanation.impl.blackbox.StructuralTypePriorityE
xpansionStrategy.doExpansion(StructuralTypePriorityExpansionStrategy.java:65)
        at org.semanticweb.owl.explanation.impl.blackbox.BlackBoxExplanationGene
rator2.doExpansion(BlackBoxExplanationGenerator2.java:258)
        at org.semanticweb.owl.explanation.impl.blackbox.BlackBoxExplanationGene
rator2.computeExplanation(BlackBoxExplanationGenerator2.java:179)
        at org.semanticweb.owl.explanation.impl.blackbox.BlackBoxExplanationGene
rator2.generateExplanation(BlackBoxExplanationGenerator2.java:289)
        at org.semanticweb.owl.explanation.impl.blackbox.hst.HittingSetTree.buil
dHittingSetTree(HittingSetTree.java:116)
        at org.semanticweb.owl.explanation.impl.blackbox.BlackBoxExplanationGene
rator2.getExplanations(BlackBoxExplanationGenerator2.java:114)
        at org.semanticweb.owl.explanation.impl.blackbox.BlackBoxExplanationGene
rator2.getExplanations(BlackBoxExplanationGenerator2.java:91)
        at uk.ac.manchester.cs.owl.explanation.JustificationManager$ExplanationG
eneratorCallable.call(JustificationManager.java:315)
        at uk.ac.manchester.cs.owl.explanation.JustificationManager$ExplanationG
eneratorCallable.call(JustificationManager.java:285)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tudorache** [comment]
This exception masks other exceptions that are being thrown, it would be good to expose those as well.
